name: deploy

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  my-job:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install
      - run: bun run build
      - name: Deploy to GitHub Pages
        run: bun run deploy
      - id: build-publish
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          path: dist # change to your build folder
